name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.13.2"]
        spark: ["3.3.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - name: Test
        run: sbt -Dspark.testVersion=${{ matrix.spark }} ++${{ matrix.scala }} test